### ISSUE TITLE
[task] Loops and conditions

### ISSUE THREAD

**Issue by gochicus** [atls-academy/frontend-study-gochicus#3]
В данном коде необходимо автоматизировать ответы пользователя при помощи цикла, при этом пользователь не должен иметь возможности ввести пустую строку, отменить ответ или ввести ответ длинною более 50 символов.  Количество фильмов должно быть записано в объекте personalMoviesDB. Результат вывести через console log.

**Comment by TorinAsakura** [comment]
@gochicus Пожалуйста, используй разметку для улучшения читабельности

**Comment by ad21ewda1231dsa123das12** [comment]
Пожалуйста, заполни сайдбар справа (в пулл реквесте, когда будешь отправлять, тоже)
