### ISSUE TITLE
[feature] New functionality for web-diary app 

### ISSUE THREAD

**Issue by gochicus** [atls-academy/frontend-study-gochicus#60]
### С чем связан запрос на фичу?
Добавить возможность добавлять посты в приложении. 

### Расскажите как вы это себе видите
Использовать props и state при выполеннии задачи. 

### Приложите примеры реализаций
[Реализация в курсе](https://github.com/yankovalenko94/JS_task_answers/tree/master/React_step_3)

**Comment by TorinAsakura** [comment]
@gochicus status?

**Comment by gochicus** [comment]
> @gochicus status?

Работа будет продолжена после рефакторинга, в настоящий момент задача не закончена.

**Comment by TorinAsakura** [comment]
> > @gochicus status?
> 
> 1. Работа будет продолжена после рефакторинга, в настоящий момент задача не закончена.

Не используй списки для единственного объекта…
Если она зависит от другой задачи - то так и напиши в конце тела задачи со ссылкой на задачу

DEPEND ON #666
