### ISSUE TITLE
[feature] create public package 

### ISSUE THREAD

**Issue by TFK70** [atls-academy/frontend-study-gochicus#81]
### С чем связан запрос на фичу?

1. Создать публичный пакет `@gochicus/list`, отвечающий за отрисовку TodoItem
2. Внедрить в проект, установив как зависимость

### Расскажите как вы это себе видите

Пакет должен быть публичным, т.е. присутствовать в [npm регистре](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages)

Пакет будет заменять `@ui/list`, API не изменится
Сам `@ui/list` нужно будет убрать, за ненадобностью

Пример использования:

```javascript
import TodoList from '@gochicus/list'

<TodoList
      deleteItem={deleteItem}
      likeItem={likeItem}
      importantItem={importantItem}
      items={filterData(postData, status, searchResult)}
    />
```

### Приложите примеры реализаций

https://github.com/atls-academy/gochicus.github.io/tree/master/practice/web-diary/ui/list

**Comment by gochicus** [comment]
@TFK70 не получается опубликовать пакет, получаю ошибку 403, текст ошибки:

> npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@practice%2fweb-diary - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aleksandr/.npm/_logs/2021-06-18T09_46_38_615Z-debug.log

Искал варианты решения, пробовал создать файл `.npmrc` и прописать в нем новый токен, как советуют [здесь](https://github.com/npm/cli/issues/805) Однако, результата это не дало.

**Comment by TFK70** [comment]
@gochicus Распиши что ты делал

**Comment by gochicus** [comment]
@TFK70 

1. npm login
2. переход в директорию пакета
3. npm init
4. Заполнил поля: имя, описание, автор, лицензия
5. Подтвердил правильность написанного в пакете
6. Посмотрел текст пакета и из поля тест убрал команду на выход в случае отсутствия теста.
7. npm publish --access=public

**Comment by TFK70** [comment]
@gochicus Где находится пакет? Как выглядит package.json? Больше данных об окружении

**Comment by gochicus** [comment]
@TFK70 пакет расположен в `web-diary/ui/list`

> {
  "name": "@ui/list",
  "version": "0.0.0",
  "license": "BSD-3-Clause",
  "main": "src/index.tsx",
  "dependencies": {
    "@store/post-data": "0.0.0",
    "@ui/background": "0.0.0",
    "@ui/button": "0.0.0",
    "@ui/condition": "0.0.0",
    "@ui/icons": "0.0.0",
    "@ui/layout": "0.0.0",
    "@ui/text": "0.0.0",
    "@ui/theme": "0.0.0",
    "react": "^17.0.1"
  },
  "description": "item iterator",
  "scripts": {
    "test": "echo \"Error: no test specified\""
  },
  "author": "gochicus"
}

**Comment by TFK70** [comment]
@gochicus https://classic.yarnpkg.com/en/docs/publishing-a-package/
create+publish

**Comment by gochicus** [comment]
@TFK70 Описываю прогресс на текущий момент и затруднения. Чтобы обойти  проблему с ошибкой 403, описанной выше, переименовал пакет в gochicus/list, и получил возможность его опубликовать. Успешно опубликовал пакет под этим именем(потом сразу же убрализ npm, когда стало ясно, что не работает), добавил во фрагмент `post-list`, однако модуль не загружался. Пытаюсь решить проблему через настройки tsconfig. Буду тестировать.  Ещё одна проблема связана с компонентом `Text` в  `Item,` получаю ошибку:

> TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    Type 'Text' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.

**Comment by TFK70** [comment]
> @TFK70 Описываю прогресс на текущий момент и затруднения. Чтобы обойти проблему с ошибкой 403, описанной выше, переименовал пакет в gochicus/list, и получил возможность его опубликовать. Успешно опубликовал пакет под этим именем(потом сразу же убрализ npm, когда стало ясно, что не работает), добавил во фрагмент `post-list`, однако модуль не загружался. Пытаюсь решить проблему через настройки tsconfig. Буду тестировать. Ещё одна проблема связана с компонентом `Text` в `Item,` получаю ошибку:
> 
> > TS2786: 'Text' cannot be used as a JSX component.
> > Its instance type 'Text' is not a valid JSX element.
> > Type 'Text' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.

1. Я более чем уверен что ты на эти проблемы потратил больше 30 минут, скорее всего несколько часов. Почему сразу о них не написал?
2. Мне кидать обрывки от логов ошибок бессмысленно пока не покажешь код & окружение (можно хоть коммитом это сделать) и это важный момент который ты всегда опускаешь
3. Смотрел ссылку которую я вчера к таске прикрепил?

**Comment by gochicus** [comment]
@TFK70 Ссылку смотрел, код сейчас закину.  По проблемам пытался сам разобраться.

**Comment by gochicus** [comment]
@TFK70  возникает проблема с парсингом кода, получаемого из пакета. Код в последнем [коммите](https://github.com/atls-academy/gochicus.github.io/pull/87). Пакет доступен в нпм `@gochicus/list:0.0.6`. Не уверен в чем проблема, то ли тут нужо как-то сделать асинхронность парсинга, то ли я в пакете что-то напутал. Собственно, текст ошибки:

> List.tsx:1 Uncaught Error: Module parse failed: Unexpected token (7:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export const List = ({ items, deleteItem, importantItem, likeItem, setPostData }) => {
|     return (
>         <Column width='100%' justifyContent='center'>
|             {items.map(item => (
|                 <ListItem
    at eval (List.tsx:1)
    at Object.../../node_modules/@gochicus/list/src/List.tsx (main.js:425)
    at __webpack_require__ (main.js:2203)
    at eval (index.tsx:2)
    at Module.../../node_modules/@gochicus/list/src/index.tsx (main.js:436)
    at __webpack_require__ (main.js:2203)
    at eval (PostList.tsx:7)
    at Module../fragments/post-list/src/PostList.tsx (main.js:766)
    at __webpack_require__ (main.js:2203)
    at eval (index.tsx:5)

**Comment by TFK70** [comment]
@gochicus давай думать почему так
Было бы неплохо если бы ты еще добавил свои догадки, например на счет того что он ссылается на вебпак. Куда копаем?

**Comment by gochicus** [comment]
@TFK70 Статус выполнения задачи. Сейчас есть 0.0.7 версия пакета (опубликована), в ней проверялось влияние tsconfig из пакета на работу приложения. В работе версия 0.0.8  в ней добавлен вебпак и .npmignore. Сейчас разбираюсь с настройками вебпака, чтобы собрать пакет, src уйдет в .npmignore. Потом будт проверяться как оно работает в рпиложении.

**Comment by TFK70** [comment]
@gochicus При локальных тестах все отрабатывает? Если сделать пакет воркспейсом и так же установить как зависимость?

**Comment by gochicus** [comment]
@TFFOE  Да, забыл протестировать версию с js локально, только на сборку тестировал.

**Comment by gochicus** [comment]
@TFK70 протестировал локально, не рендерится. Вероятно, не дописал в конфигах типы, попробую исправить. Текст ошибки: 

> react.development.js:219 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PostList`.
    at PostList (webpack://@practice/web-diary/./fragments/post-list/src/PostList.tsx?:33:83)
    at div
    at Styled(div) (webpack://@practice/web-diary/../../node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js?:45:66)
    at div
    at Styled(div) (webpack://@practice/web-diary/../../node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js?:45:66)
    at div
    at Styled(div) (webpack://@practice/web-diary/../../node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js?:45:66)
    at div
    at Styled(div) (webpack://@practice/web-diary/../../node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js?:45:66)
    at Diary
    at ThemeProvider (webpack://@practice/web-diary/../../node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js?:81:64)
    at ThemeProvider
    at IntlProvider (webpack://@practice/web-diary/../../node_modules/react-intl/lib/src/components/provider.js?:104:43)

**Comment by TFK70** [comment]
@gochicus Обычно это происходит если забываешь экспортировать/импортировать компонент. Если не забыл - проверь return у PostList, удостоверься что он возвращает jsx

**Comment by gochicus** [comment]
@TFK70  Возвращает он вот это:

> import {List} from "../../../../../list/dist/main.js";
export const PostList = () => {
  const [postData, setPostData] = usePostData()
  const [status] = useButtonStatus()
  const [searchResult] = useSearchValue()
  return (
    <Row justifyContent='center'>
      <List
        deleteItem={deleteItem}
        likeItem={likeItem}
        importantItem={importantItem}
        items={filterData(postData, status, searchResult)}
        setPostData={setPostData}
      />
    </Row>
  )
}

Тут List тянет напрямую  js собранный.

**Comment by TFK70** [comment]
@gochicus Так он у тебя ничего не импортирует, и выглядит это странно. Ты с js работать не должен, весь твой ts сбилдится в js после

**Comment by gochicus** [comment]
@TFK70 Так я сколько пытался этот момент  [прояснить](https://github.com/atls-academy/gochicus.github.io/pull/87#discussion_r659631796) и так понял, что js  быть должен, ведь как иначе, если пакет должен возвращать только js.
