### ISSUE TITLE
[feature] implement example project

### ISSUE THREAD

**Issue by TFK70** [atls-academy/frontend-study-gochicus#83]
### С чем связан запрос на фичу?

Сверстать example

#### Скелет:

https://user-images.githubusercontent.com/62806448/119334882-0b4aa880-bca5-11eb-8a8e-7394aea4bb7a.mov

**Comment by TFK70** [comment]
@gochicus 

1. Примерная идея приложения которую мы реализовывали + пища для размышления в контексте нашей проблемы:
https://ru.reactjs.org/docs/lifting-state-up.html - отсюда ты должен понять как и почему это работает и спроецировать на свой инпут (как те же самые атрибуты обрабатываются у тебя)

2. Тут обрати внимание только на код и постарайся понять как и почему он работает: https://habr.com/ru/post/503700/

**Comment by gochicus** [comment]
@TFK70 Если передавать всю логику onClick в ColorPicker, который расположен в Controls, каким образом передать туда значения текущего цвета кнопки, не используя состояния в ColorPicker?
` <ColorPicker onClick={setValue()} colors={['red', 'green', 'blue']} />`

**Comment by TFK70** [comment]
@gochicus я вообще ничего не понял, приведи код, опиши проблему, задай хоть какой-то контекст

**Comment by TorinAsakura** [comment]
@gochicus У меня пожалуй лишь один вопрос: а что у тебя за логика в onClick?

**Comment by gochicus** [comment]
@TorinAsakura ` <ColorPicker onClick={setValue()} colors={['red', 'green', 'blue']} />` По клику должно задаваться состоянее, соответствующее текущему значению цвета у кнопки.

**Comment by TFK70** [comment]
@gochicus ты можешь передать туда коллбек и вызывать его внутри с нужными параметрами, как ты делал в store с usePostData, например
